language: node_js
node_js:
- 10.1.0
cache:
  yarn: true
script:
- yarn install
- yarn gatsby build
- touch public/.nojekyll
- echo "beta.pandala.org" >public/CNAME
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  local-dir: "./public"
  keep-history: false
  skip-cleanup: true
  target-branch: gh-pages
  on:
    branch: master
env:
  global:
    secure: ILQfAxMNj7x+NEVmutlBahwiDcITHD3By3l9fzfmd048y5EhhRELV/gMd699Apm7pOKrb0S0Wr8t+qo9DjF+S0Rgr4USK7Pweghirtt7X7EcEno3kzeq5jvZfqtOmKuNAF/Ahv9HvGDY8ShPgZpqFcqkuH43HQhP49P5y6J49neiBqOUvbLYU2+qqk+PgvvSBaM96DFmekw7bO2xLScsbCNJBECCD4oVM/IHtbN32vmmRpodFTcygvmm3L21cE5HoxN8zgyXZ75Yr5udjaMLNqihRyFiyqBXBW3yW6FaurSq9rsVgG6co8uADDcWpoJyX99j6fwnVX7XbwCfsfYnjHCOUC09flgzTq35uypkFYev7SXuCcCGIcFk2O5tc4Sj+iJgmdLPWfFNJnlAq7dRlw3wFrcPt9zMxtjl+kvsKFb7Z6WrdG7sVPPOwG2RwP4o+YxnjA2x2jMMP11YhnfmmOXTt6htDNLaL9oFJ7uZZvAaiRfC67ecxRlzV62Dy/oQEgWuVmRoxKBHSXVIAd29ME9qRc+KpP60/dP2e3Pg9x0et5hrv60gUYtY1m9gYh4ZVubAmQfF5iyvAqr1pmOrEC/QuBQUNGZdQo4jIptxBI0OXON4sY+7QnSLX79DBJUnCSIwR8xLRrQiuv+hIEf+W7Nql4h6u9tCG29+TQ+MdNI=
