name: "build"
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: datakurre
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: >
        nix-build;
        cp -aL result/.cache .;
        cp -aL result/public .;
        chmod a+w -R .cache public;
        cp -aL public build;
        rm result
    - run: nix-shell shell.nix --run "echo OK"
    - run: nix-shell default.nix --run "echo OK"
    - name: Cache GatsbyJS build
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache
          ~/public
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: build
        single-commit: true
